### PR TITLE
make keynav work in different layout

### PR DESCRIPTION
**Pull request by seletskiy**
keynav will not work if layout is differ from default. XKB cause `e->state` to be `8192` if layout group has changed.

### CODE REVIEW

**Comment by kovetskiy** [comment]
@jordansissel zaebal, zamerje uje

**Comment by seletskiy** [comment]
@jordansissel: ping?

**Comment by sojusnik** [comment]
Same here. When launching keynav with russian layout, keynav shows only the start frame, without reacting at all, so that you have to terminate it manually.

Please merge this asap. Thanks!

**Comment by jordansissel** [comment]
@seletskiy sorry for the delays. This PR looks pretty large compared to the change described - Did you mean to only submit https://github.com/seletskiy/keynav/commit/16210d5326bd172da9fa1ecbb34eaa3d52eadbb9 for this pr, and not including https://github.com/seletskiy/keynav/commit/e6d03b0da5597460138f0c8414251536121efb68?

**Comment by sojusnik** [comment]
Please include both, since they are both working and useful. The improved
grid looks definitely better, than the old one, imho.

Jordan Sissel <notifications@github.com> schrieb am Do., 14. Jän. 2016
09:33:

**Comment by seletskiy** [comment]
@jordansissel: First commit is for fixing layout issues, indeed. Second is for drawing more precise grid and fixing crash when grid is too small, I didn't want to create separate PRs when I had done that changes. If you insist, I can create separate PR for the next one, but I see no problems in merging it that way.

**Pull request merged**
